# -*- coding: utf-8 -*-
"""kalkulator suhu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l45iQdqUtLIatuFSPAbPQbaELnbttb59
"""

!pip install streamlit pyngrok --quiet

kode = """
def convert_suhu():
    st.title("Kalkulator Konversi Suhu")

    st.subheader("Pilih jenis konversi suhu")
    pilihan = st.radio(
        "Pilih konversi suhu:",
        ("Celcius ke Fahrenheit", "Celcius ke Kelvin", "Fahrenheit ke Celcius", "Fahrenheit ke Kelvin", "Kelvin ke Celcius", "Kelvin ke Fahrenheit")
    )

    if pilihan == "Celcius ke Fahrenheit":
        celsius = st.number_input("Masukkan suhu dalam Celcius (°C):")
        if celsius is not None:
            fahrenheit = (celsius * 9/5) + 32
            st.write(f"{celsius}°C = {fahrenheit}°F")

    elif pilihan == "Celcius ke Kelvin":
        celsius = st.number_input("Masukkan suhu dalam Celcius (°C):")
        if celsius is not None:
            kelvin = celsius + 273.15
            st.write(f"{celsius}°C = {kelvin} K")

    elif pilihan == "Fahrenheit ke Celcius":
        fahrenheit = st.number_input("Masukkan suhu dalam Fahrenheit (°F):")
        if fahrenheit is not None:
            celsius = (fahrenheit - 32) * 5/9
            st.write(f"{fahrenheit}°F = {celsius}°C")

    elif pilihan == "Fahrenheit ke Kelvin":
        fahrenheit = st.number_input("Masukkan suhu dalam Fahrenheit (°F):")
        if fahrenheit is not None:
            kelvin = (fahrenheit - 32) * 5/9 + 273.15
            st.write(f"{fahrenheit}°F = {kelvin} K")

    elif pilihan == "Kelvin ke Celcius":
        kelvin = st.number_input("Masukkan suhu dalam Kelvin (K):")
        if kelvin is not None:
            celsius = kelvin - 273.15
            st.write(f"{kelvin} K = {celsius}°C")

    elif pilihan == "Kelvin ke Fahrenheit":
        kelvin = st.number_input("Masukkan suhu dalam Kelvin (K):")
        if kelvin is not None:
            fahrenheit = (kelvin - 273.15) * 9/5 + 32
            st.write(f"{kelvin} K = {fahrenheit}°F")

"""

with open("bmi_app.py", "w") as f:
    f.write(kode)

!ngrok config add-authtoken 2uzt3zck7DsFcgSphPuyEpHgUiN_3gijm7UyXNThGByqVsBhA

!pkill -f streamlit

from pyngrok import ngrok

# Jalankan streamlit sebagai background process
!streamlit run bmi_app.py &>/dev/null &

# Hubungkan ke Streamlit via ngrok (versi baru)
public_url = ngrok.connect(addr="8501", proto="http")
print("Aplikasi bisa diakses di link berikut:")
print(public_url)