# -*- coding: utf-8 -*-
"""Kalkulator Trigonometri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yfj4NCY0dBFkmK55wajprFAN_LD4JTwP
"""

!pip install streamlit pyngrok --quiet

kode = """
import streamlit as st
import numpy as np
import plotly.graph_objs as go

st.set_page_config(page_title="Virtual Lab Trigonometri", layout="wide")

st.title("🧪 Virtual Lab Interaktif: Trigonometri")

# Sidebar controls
st.sidebar.header("🔧 Atur Parameter Fungsi Trigonometri")
func_type = st.sidebar.selectbox("Pilih Fungsi:", ["sin(x)", "cos(x)", "tan(x)"])
amplitude = st.sidebar.slider("Amplitudo", 0.5, 5.0, 1.0, 0.1)
frequency = st.sidebar.slider("Frekuensi", 0.5, 5.0, 1.0, 0.1)
phase = st.sidebar.slider("Fase (rad)", -np.pi, np.pi, 0.0, 0.1)

# Data
x = np.linspace(-2*np.pi, 2*np.pi, 1000)
if func_type == "sin(x)":
    y = amplitude * np.sin(frequency * x + phase)
elif func_type == "cos(x)":
    y = amplitude * np.cos(frequency * x + phase)
else:  # tan(x)
    y = amplitude * np.tan(frequency * x + phase)
    y[np.abs(y) > 10] = np.nan  # filter ledakan vertikal pada tan

# Grafik fungsi trigonometri
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y, mode="lines", name=func_type))
fig.update_layout(title=f"Grafik Fungsi {func_type}",
                  xaxis_title="x (radian)",
                  yaxis_title="y",
                  height=500)

st.plotly_chart(fig, use_container_width=True)

# Lingkaran Trigonometri
st.subheader("🌀 Visualisasi Lingkaran Trigonometri")
theta = st.slider("Sudut (derajat)", 0, 360, 45)

angle_rad = np.deg2rad(theta)
x_unit = np.cos(angle_rad)
y_unit = np.sin(angle_rad)

fig2 = go.Figure()
# Lingkaran satuan
circle_x = np.cos(np.linspace(0, 2*np.pi, 100))
circle_y = np.sin(np.linspace(0, 2*np.pi, 100))
fig2.add_trace(go.Scatter(x=circle_x, y=circle_y, mode='lines', name='Lingkaran Satuan'))
# Radius
fig2.add_trace(go.Scatter(x=[0, x_unit], y=[0, y_unit], mode='lines+markers', name='Radius'))
# Proyeksi sumbu
fig2.add_trace(go.Scatter(x=[x_unit, x_unit], y=[0, y_unit], mode='lines', line=dict(dash='dash'), name='Proyeksi Cos'))
fig2.add_trace(go.Scatter(x=[0, x_unit], y=[y_unit, y_unit], mode='lines', line=dict(dash='dash'), name='Proyeksi Sin'))

fig2.update_layout(width=500, height=500, xaxis_range=[-1.5, 1.5], yaxis_range=[-1.5, 1.5],
                   title="Lingkaran Trigonometri", showlegend=True)

st.plotly_chart(fig2)

st.markdown("---")
st.markdown("Dibuat dengan ❤️ menggunakan Python + Streamlit")
"""

with open("bmi_app.py", "w") as f:
    f.write(kode)

!ngrok config add-authtoken 2uzt3zck7DsFcgSphPuyEpHgUiN_3gijm7UyXNThGByqVsBhA

from pyngrok import ngrok

# Jalankan streamlit sebagai background process
!streamlit run bmi_app.py &>/dev/null &

# Hubungkan ke Streamlit via ngrok (versi baru)
public_url = ngrok.connect(addr="8533", proto="http")
print("Aplikasi bisa diakses di link berikut:")
print(public_url)